"""Derive Windows packaging assets from the reviewed identity and generated artwork."""
import json
from pathlib import Path
from PIL import Image, ImageColor

ROOT=Path(__file__).resolve().parents[1]
assets=ROOT/'assets/identity'
product=json.loads((assets/'product.json').read_text(encoding='utf-8-sig'))
tokens=json.loads((ROOT/'assets/brand.json').read_text(encoding='utf-8-sig'))
out=ROOT/'build/brand';out.mkdir(parents=True,exist_ok=True)
icon=Image.open(assets/'fate-icon-source.png').convert('RGBA')
icon.save(assets/'fate-engine.ico',sizes=[(n,n) for n in (16,24,32,48,64,128,256)])
# Lossless source artwork stays untouched; these are installer-size renditions.
small=Image.new('RGB',(64,64),ImageColor.getrgb(tokens['surface']['base']))
small.paste(icon.resize((64,64),Image.Resampling.LANCZOS),(0,0),icon.resize((64,64),Image.Resampling.LANCZOS))
small.save(assets/'installer-mark.bmp')
if (assets/'installer-panel-source.png').exists():
    panel=Image.open(assets/'installer-panel-source.png').convert('RGB')
    panel.resize((342,628),Image.Resampling.LANCZOS).save(assets/'installer-panel.bmp')

def wincolor(value):
    r,g,b=ImageColor.getrgb(value);return r+(g<<8)+(b<<16)
constants={'ProductName':product['name'],'ProductSubtitle':product['subtitle'],
           'ProductVersion':product['version'],'ProductExe':product['executable'],
           'ProductAppId':product['app_user_model_id']}
text='// Generated by tools/build_product_assets.py\n'
for key,value in constants.items():text+=f'#define {key} "{value}"\n'
text+=f"#define BrandSurface {wincolor(tokens['surface']['base'])}\n"
text+=f"#define BrandGold {wincolor(tokens['accent']['default'])}\n"
(out/'product.iss').write_text(text,encoding='utf-8')
version=tuple(map(int,product['version'].split('.')))+(0,)
for filename in (product['executable'],'EndfieldManager.exe'):
    fields={'CompanyName':product['publisher'],'FileDescription':product['name']+' - '+product['subtitle'],
            'FileVersion':product['version'],'InternalName':Path(filename).stem,
            'OriginalFilename':filename,'ProductName':product['name'],
            'ProductVersion':product['version'],'LegalCopyright':'Copyright 2026 '+product['publisher']}
    pairs=',\n'.join(f'StringStruct({key!r}, {value!r})' for key,value in fields.items())
    resource=f"VSVersionInfo(ffi=FixedFileInfo(filevers={version!r}, prodvers={version!r}, mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0,0)), kids=[StringFileInfo([StringTable('040904B0', [{pairs}])]), VarFileInfo([VarStruct('Translation', [1033,1200])])])"
    (out/(Path(filename).stem+'-version.txt')).write_text(resource,encoding='utf-8')
print('Generated icon frames, installer branding, and executable version resources')
